FROM node:20-alpine

WORKDIR /app
RUN apk add --no-cache openssl

COPY package.json ./
COPY api/package.json ./api/package.json
COPY web/package.json ./web/package.json
RUN npm install

COPY api ./api

WORKDIR /app/api
RUN npx prisma generate && npm run build

EXPOSE 4000
CMD ["sh", "-c", "npx prisma migrate deploy && npm run prisma:seed && npm run start"]
